<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>project_api_reciclaAi</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DataContexts\" />
    <Folder Include="Dtos\Cliente\" />
    <Folder Include="Dtos\Catador\" />
    <Folder Include="Dtos\Endereco\" />
    <Folder Include="Dtos\Empresa\" />
    <Folder Include="Dtos\EquipeColeta\" />
    <Folder Include="Dtos\Foto\" />
    <Folder Include="Dtos\Coleta\" />
    <Folder Include="Dtos\Avaliacao\" />
    <Folder Include="Dtos\Solicitacao\" />
    <Folder Include="Dtos\TipoMaterial\" />
    <Folder Include="Dtos\TipoUsuario\" />
    <Folder Include="Exceptions\" />
    <Folder Include="Profiles\" />
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
